### ISSUE TITLE
svg fill blocking the web-3-onboard component in bottom right corner after connecting

### ISSUE THREAD

**Issue by tantodefi** [lukso-network/tools-dapp-boilerplate#13] opened 2024-01-04 22:53 UTC
After connecting UP extension with web3-onboard-library,
There is an svg that renders blocking the "3 dot menu" in the web-3-onboard widget

![Screenshot 2024-01-04 at 4 46 01 PM](https://github.com/lukso-network/tools-dapp-boilerplate/assets/107724252/2303b143-a6d2-499f-b765-a38943a70b8c)

I tried this on both desktop and tablet breakpoints and same result.

I actually think this blocking SVG may be a bug in web3-onboard v2 but I'm not sure.

I checked their implementation on their site and it seems to work fine so actually I wonder if this is an issue with how UP was added as a wallet/login provider to the webs3-onboard library ? 

![Screenshot 2024-01-05 at 11 24 21 AM](https://github.com/lukso-network/tools-dapp-boilerplate/assets/107724252/f733cc9c-8b32-4517-b407-add94085ff11)

**Comment by fhildeb** [comment] 2024-01-25 14:55
Thanks for your feedback, Tanto! I will check and try to resolve this.

**Comment by fhildeb** [comment] 2024-02-08 23:56
This issue is related to our `@lukso/web3-onboard-config@1.1.1` library- which updated the SVG.

It seems there is something wrong with how the SVG is attached. The problem does not exist on version `@1.1.0`

I will create a new release tomorrow and update the library version on this repository. 👍🏻

**Comment by fhildeb** [comment] 2024-02-12 16:40
Alright- sorry for the delay on the release. I did it myself today. The issue is resolved with #36 🙏🏻. This will also include any other app that updates the `@lukso/web3-onboard-config` lib to `v.1.1.2`

**Closed** 2024-02-13 09:55 UTC
